### ISSUE TITLE
incorrect PromptIfStale override

### ISSUE THREAD

**Issue by karenetheridge** [autarch/Dist-Zilla-PluginBundle-DROLSKY#2]
re your last release "Make the PromptIfStale plugin skip all inc::* packages that live in the inc/ dir." -- that change would be a mistake, as if you are seeing a Prompt for an inc:: module, that means it's showing up in your published prereq list, as the plugin only checks prereqs from metadata.

Instead of excluding the module from PromptIfStale, you should remove the inc:: plugins from your prereqs.

**Comment by autarch** [comment]
This makes sense but I don't see how I can do this with authordeps. The dzil core code extracts this by reading the `dist.ini` file directly in `Dist::Zilla::Util::AuthorDeps::extract_author_deps($self->zilla->root)`. AFAICT there's no opportunity to pass a filter to the code that scans for authordeps.

**Comment by karenetheridge** [comment]
PromptIfStale 0.056 does that now. I looked into it a bit more after I filed this. :)

**Comment by autarch** [comment]
I uploaded 1.08 of my bundle which requires PromptIfStale 0.056 and reverts the change I made to my bundle.
